import { Container, Header } from '@/shared/components/shared';
import { Metadata } from 'next';
import React, { Suspense } from 'react';

export const metadata: Metadata = {
  title: 'More Pro Pizza | Корзина',
  description: 'Generated by create next app',
};

export default function CheckoutLayout({ children }: { children: React.ReactNode }) {
  return (
    <main className="min-h-screen bg-[#f4f1ee]">
      <Container>
        <Suspense>
          <Header hasSearch={false} hasCart={false} className="border-b-gray" />
        </Suspense>
        {children}
      </Container>
    </main>
  );
}
